"""Auto-generated endpoint tests from the OpenAPI spec.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_endpoint_tests.py` to regenerate.
"""

import pytest

from onepostly.api.connections_api import ConnectionsApi
from onepostly.api.media_api import MediaApi
from onepostly.api.posts_api import PostsApi
from onepostly.api.analytics_api import AnalyticsApi
from onepostly.api.comments_api import CommentsApi
from onepostly.api.inbox_api import InboxApi
from onepostly.api.engagement_api import EngagementApi
from onepostly.api.webhooks_api import WebhooksApi


@pytest.mark.parametrize(
    "api_class, method_name",
    [
        (ConnectionsApi, "connect_bluesky"),
        (ConnectionsApi, "create_pinterest_board"),
        (ConnectionsApi, "create_profile"),
        (ConnectionsApi, "delete_profile"),
        (ConnectionsApi, "get_bluesky_settings"),
        (ConnectionsApi, "get_connection_stats"),
        (ConnectionsApi, "get_tik_tok_creator_info"),
        (ConnectionsApi, "list_connection_media"),
        (ConnectionsApi, "list_connections"),
        (ConnectionsApi, "list_facebook_pages"),
        (ConnectionsApi, "list_instagram_accounts"),
        (ConnectionsApi, "list_pinterest_boards"),
        (ConnectionsApi, "list_profiles"),
        (ConnectionsApi, "select_facebook_page"),
        (ConnectionsApi, "select_instagram_account"),
        (ConnectionsApi, "set_connection_messenger_profile"),
        (ConnectionsApi, "start_o_auth"),
        (ConnectionsApi, "update_bluesky_settings"),
        (MediaApi, "delete_media"),
        (MediaApi, "get_media_presigned_url"),
        (MediaApi, "list_media"),
        (PostsApi, "cancel_post"),
        (PostsApi, "create_post"),
        (PostsApi, "delete_post_destination"),
        (PostsApi, "get_post"),
        (PostsApi, "list_posts"),
        (PostsApi, "sync_external"),
        (AnalyticsApi, "get_analytics"),
        (AnalyticsApi, "get_analytics_timeline"),
        (CommentsApi, "create_comment"),
        (CommentsApi, "create_private_reply"),
        (CommentsApi, "delete_comment"),
        (CommentsApi, "hide_comment"),
        (CommentsApi, "like_comment"),
        (CommentsApi, "list_comments"),
        (CommentsApi, "unlike_comment"),
        (InboxApi, "create_inbox_conversation"),
        (InboxApi, "list_inbox_conversations"),
        (InboxApi, "list_inbox_messages"),
        (InboxApi, "send_inbox_message"),
        (EngagementApi, "bookmark"),
        (EngagementApi, "create_automation"),
        (EngagementApi, "delete_automations"),
        (EngagementApi, "like"),
        (EngagementApi, "list_automations"),
        (EngagementApi, "list_retweeters"),
        (EngagementApi, "quote"),
        (EngagementApi, "remove_bookmark"),
        (EngagementApi, "retweet"),
        (EngagementApi, "undo_retweet"),
        (EngagementApi, "unlike"),
        (WebhooksApi, "create_webhook"),
        (WebhooksApi, "delete_webhook"),
        (WebhooksApi, "get_webhook"),
        (WebhooksApi, "get_webhook_delivery_summary"),
        (WebhooksApi, "list_webhook_deliveries"),
        (WebhooksApi, "list_webhook_event_types"),
        (WebhooksApi, "list_webhooks"),
        (WebhooksApi, "test_webhook"),
        (WebhooksApi, "update_webhook"),
    ],
)
def test_spec_endpoints_surface_as_sdk_methods(api_class, method_name):
    """Every spec operation must exist as a method on its API class."""
    assert callable(getattr(api_class, method_name, None))
