# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Connection(BaseModel):
    """
    Connection
    """ # noqa: E501
    id: UUID
    platform: StrictStr
    display_name: StrictStr = Field(alias="displayName")
    handle: StrictStr
    avatar_url: Optional[StrictStr] = Field(alias="avatarUrl")
    status: StrictStr
    token_expires_at: Optional[datetime] = Field(alias="tokenExpiresAt")
    can_auto_renew: StrictBool = Field(alias="canAutoRenew")
    auth_health: StrictStr = Field(alias="authHealth")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "platform", "displayName", "handle", "avatarUrl", "status", "tokenExpiresAt", "canAutoRenew", "authHealth", "createdAt", "updatedAt"]

    @field_validator('auth_health')
    def auth_health_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['healthy', 'action_required']):
            raise ValueError("must be one of enum values ('healthy', 'action_required')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Connection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if avatar_url (nullable) is None
        # and model_fields_set contains the field
        if self.avatar_url is None and "avatar_url" in self.model_fields_set:
            _dict['avatarUrl'] = None

        # set to None if token_expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.token_expires_at is None and "token_expires_at" in self.model_fields_set:
            _dict['tokenExpiresAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Connection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "platform": obj.get("platform"),
            "displayName": obj.get("displayName"),
            "handle": obj.get("handle"),
            "avatarUrl": obj.get("avatarUrl"),
            "status": obj.get("status"),
            "tokenExpiresAt": obj.get("tokenExpiresAt"),
            "canAutoRenew": obj.get("canAutoRenew"),
            "authHealth": obj.get("authHealth"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


