# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreatePostBodyDestinationsInner(BaseModel):
    """
    CreatePostBodyDestinationsInner
    """ # noqa: E501
    connection_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="connectionId")
    text: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = None
    quote_tweet_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]] = Field(default=None, alias="quoteTweetId")
    privacy_status: Optional[StrictStr] = Field(default=None, alias="privacyStatus")
    privacy_level: Optional[StrictStr] = Field(default=None, alias="privacyLevel")
    disable_comment: Optional[StrictBool] = Field(default=None, alias="disableComment")
    disable_duet: Optional[StrictBool] = Field(default=None, alias="disableDuet")
    disable_stitch: Optional[StrictBool] = Field(default=None, alias="disableStitch")
    brand_organic_toggle: Optional[StrictBool] = Field(default=None, alias="brandOrganicToggle")
    brand_content_toggle: Optional[StrictBool] = Field(default=None, alias="brandContentToggle")
    description: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = None
    board_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(default=None, description="Pinterest only. Required for Pinterest destinations.", alias="boardId")
    link: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = None
    title: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=300)]] = None
    subreddit: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = None
    flair_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(default=None, alias="flairId")
    flair_text: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(default=None, alias="flairText")
    nsfw: Optional[StrictBool] = None
    spoiler: Optional[StrictBool] = None
    thumbnail_url: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = Field(default=None, alias="thumbnailUrl")
    __properties: ClassVar[List[str]] = ["connectionId", "text", "quoteTweetId", "privacyStatus", "privacyLevel", "disableComment", "disableDuet", "disableStitch", "brandOrganicToggle", "brandContentToggle", "description", "boardId", "link", "title", "subreddit", "flairId", "flairText", "nsfw", "spoiler", "thumbnailUrl"]

    @field_validator('privacy_status')
    def privacy_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['public', 'private', 'unlisted']):
            raise ValueError("must be one of enum values ('public', 'private', 'unlisted')")
        return value

    @field_validator('privacy_level')
    def privacy_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['PUBLIC_TO_EVERYONE', 'MUTUAL_FOLLOW_FRIENDS', 'FOLLOWER_OF_CREATOR', 'SELF_ONLY']):
            raise ValueError("must be one of enum values ('PUBLIC_TO_EVERYONE', 'MUTUAL_FOLLOW_FRIENDS', 'FOLLOWER_OF_CREATOR', 'SELF_ONLY')")
        return value

    @field_validator('subreddit', mode="before")
    def subreddit_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[A-Za-z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9_]+$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePostBodyDestinationsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePostBodyDestinationsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "connectionId": obj.get("connectionId"),
            "text": obj.get("text"),
            "quoteTweetId": obj.get("quoteTweetId"),
            "privacyStatus": obj.get("privacyStatus"),
            "privacyLevel": obj.get("privacyLevel"),
            "disableComment": obj.get("disableComment"),
            "disableDuet": obj.get("disableDuet"),
            "disableStitch": obj.get("disableStitch"),
            "brandOrganicToggle": obj.get("brandOrganicToggle"),
            "brandContentToggle": obj.get("brandContentToggle"),
            "description": obj.get("description"),
            "boardId": obj.get("boardId"),
            "link": obj.get("link"),
            "title": obj.get("title"),
            "subreddit": obj.get("subreddit"),
            "flairId": obj.get("flairId"),
            "flairText": obj.get("flairText"),
            "nsfw": obj.get("nsfw"),
            "spoiler": obj.get("spoiler"),
            "thumbnailUrl": obj.get("thumbnailUrl")
        })
        return _obj


