# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DestinationStatus(str, Enum):
    """
    DestinationStatus
    """

    """
    allowed enum values
    """
    QUEUED = 'queued'
    PROCESSING = 'processing'
    PUBLISHED = 'published'
    FAILED = 'failed'
    SCHEDULED = 'scheduled'
    CANCELLED = 'cancelled'
    DELETED = 'deleted'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DestinationStatus from a JSON string"""
        return cls(json.loads(json_str))


