# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from onepostly.models.normalized_metrics import NormalizedMetrics
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner(BaseModel):
    """
    GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner
    """ # noqa: E501
    day: StrictStr
    metrics: Optional[NormalizedMetrics] = None
    delta: Optional[NormalizedMetrics] = None
    __properties: ClassVar[List[str]] = ["day", "metrics", "delta"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metrics
        if self.metrics:
            _dict['metrics'] = self.metrics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of delta
        if self.delta:
            _dict['delta'] = self.delta.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "day": obj.get("day"),
            "metrics": NormalizedMetrics.from_dict(obj["metrics"]) if obj.get("metrics") is not None else None,
            "delta": NormalizedMetrics.from_dict(obj["delta"]) if obj.get("delta") is not None else None
        })
        return _obj


