# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from onepostly.models.get_analytics200_response_analytics_subjects_inner import GetAnalytics200ResponseAnalyticsSubjectsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetAnalytics200ResponseAnalytics(BaseModel):
    """
    GetAnalytics200ResponseAnalytics
    """ # noqa: E501
    post: StrictStr
    status: Optional[StrictStr] = None
    fetched_at: Optional[StrictStr] = Field(default=None, alias="fetchedAt")
    subjects: Optional[List[GetAnalytics200ResponseAnalyticsSubjectsInner]] = None
    __properties: ClassVar[List[str]] = ["post", "status", "fetchedAt", "subjects"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetAnalytics200ResponseAnalytics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in subjects (list)
        _items = []
        if self.subjects:
            for _item_subjects in self.subjects:
                _items.append(_item_subjects.to_dict() if _item_subjects is not None else None)
            _dict['subjects'] = _items
        # set to None if fetched_at (nullable) is None
        # and model_fields_set contains the field
        if self.fetched_at is None and "fetched_at" in self.model_fields_set:
            _dict['fetchedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetAnalytics200ResponseAnalytics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "post": obj.get("post"),
            "status": obj.get("status"),
            "fetchedAt": obj.get("fetchedAt"),
            "subjects": [GetAnalytics200ResponseAnalyticsSubjectsInner.from_dict(_item) for _item in obj["subjects"]] if obj.get("subjects") is not None else None
        })
        return _obj


