# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from onepostly.models.list_webhook_deliveries200_response_deliveries_inner import ListWebhookDeliveries200ResponseDeliveriesInner
from onepostly.models.list_webhook_deliveries200_response_facets import ListWebhookDeliveries200ResponseFacets
from onepostly.models.list_webhook_deliveries200_response_histogram_inner import ListWebhookDeliveries200ResponseHistogramInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListWebhookDeliveries200Response(BaseModel):
    """
    ListWebhookDeliveries200Response
    """ # noqa: E501
    deliveries: List[ListWebhookDeliveries200ResponseDeliveriesInner]
    next_cursor: Optional[StrictStr] = Field(alias="nextCursor")
    facets: ListWebhookDeliveries200ResponseFacets
    histogram: List[ListWebhookDeliveries200ResponseHistogramInner]
    __properties: ClassVar[List[str]] = ["deliveries", "nextCursor", "facets", "histogram"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListWebhookDeliveries200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in deliveries (list)
        _items = []
        if self.deliveries:
            for _item_deliveries in self.deliveries:
                _items.append(_item_deliveries.to_dict() if _item_deliveries is not None else None)
            _dict['deliveries'] = _items
        # override the default output from pydantic by calling `to_dict()` of facets
        if self.facets:
            _dict['facets'] = self.facets.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in histogram (list)
        _items = []
        if self.histogram:
            for _item_histogram in self.histogram:
                _items.append(_item_histogram.to_dict() if _item_histogram is not None else None)
            _dict['histogram'] = _items
        # set to None if next_cursor (nullable) is None
        # and model_fields_set contains the field
        if self.next_cursor is None and "next_cursor" in self.model_fields_set:
            _dict['nextCursor'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListWebhookDeliveries200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "deliveries": [ListWebhookDeliveries200ResponseDeliveriesInner.from_dict(_item) for _item in obj["deliveries"]] if obj.get("deliveries") is not None else None,
            "nextCursor": obj.get("nextCursor"),
            "facets": ListWebhookDeliveries200ResponseFacets.from_dict(obj["facets"]) if obj.get("facets") is not None else None,
            "histogram": [ListWebhookDeliveries200ResponseHistogramInner.from_dict(_item) for _item in obj["histogram"]] if obj.get("histogram") is not None else None
        })
        return _obj


