# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from onepostly.models.list_posts200_response_facets_platform_inner import ListPosts200ResponseFacetsPlatformInner
from onepostly.models.list_posts200_response_facets_status_inner import ListPosts200ResponseFacetsStatusInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListPosts200ResponseFacets(BaseModel):
    """
    ListPosts200ResponseFacets
    """ # noqa: E501
    status: List[ListPosts200ResponseFacetsStatusInner]
    platform: List[ListPosts200ResponseFacetsPlatformInner]
    __properties: ClassVar[List[str]] = ["status", "platform"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListPosts200ResponseFacets from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in status (list)
        _items = []
        if self.status:
            for _item_status in self.status:
                _items.append(_item_status.to_dict() if _item_status is not None else None)
            _dict['status'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in platform (list)
        _items = []
        if self.platform:
            for _item_platform in self.platform:
                _items.append(_item_platform.to_dict() if _item_platform is not None else None)
            _dict['platform'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListPosts200ResponseFacets from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": [ListPosts200ResponseFacetsStatusInner.from_dict(_item) for _item in obj["status"]] if obj.get("status") is not None else None,
            "platform": [ListPosts200ResponseFacetsPlatformInner.from_dict(_item) for _item in obj["platform"]] if obj.get("platform") is not None else None
        })
        return _obj


