# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListAutomations200ResponseRulesInner(BaseModel):
    """
    ListAutomations200ResponseRulesInner
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    kind: StrictStr
    keywords: List[StrictStr] = Field(description="Case-insensitive substring triggers. Empty means every comment or message matches.")
    exclude_keywords: List[StrictStr] = Field(description="Skip the rule when the comment or message contains any of these.", alias="excludeKeywords")
    dm_message: StrictStr = Field(alias="dmMessage")
    enabled: StrictBool
    account_id: StrictStr = Field(alias="accountId")
    __properties: ClassVar[List[str]] = ["id", "name", "kind", "keywords", "excludeKeywords", "dmMessage", "enabled", "accountId"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['comment_to_dm', 'story_reply', 'welcome_dm']):
            raise ValueError("must be one of enum values ('comment_to_dm', 'story_reply', 'welcome_dm')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListAutomations200ResponseRulesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListAutomations200ResponseRulesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "kind": obj.get("kind"),
            "keywords": obj.get("keywords"),
            "excludeKeywords": obj.get("excludeKeywords"),
            "dmMessage": obj.get("dmMessage"),
            "enabled": obj.get("enabled"),
            "accountId": obj.get("accountId")
        })
        return _obj


