# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from onepostly.models.comment import Comment
from onepostly.models.get_analytics200_response_analytics_subjects_inner_error import GetAnalytics200ResponseAnalyticsSubjectsInnerError
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListComments200ResponseCommentsSubjectsInner(BaseModel):
    """
    ListComments200ResponseCommentsSubjectsInner
    """ # noqa: E501
    scope: StrictStr
    subject_id: StrictStr = Field(alias="subjectId")
    account_id: StrictStr = Field(alias="accountId")
    platform: StrictStr
    external_post_id: Optional[StrictStr] = Field(alias="externalPostId")
    status: StrictStr
    comments: List[Comment]
    next_cursor: Optional[StrictStr] = Field(alias="nextCursor")
    error: Optional[GetAnalytics200ResponseAnalyticsSubjectsInnerError]
    __properties: ClassVar[List[str]] = ["scope", "subjectId", "accountId", "platform", "externalPostId", "status", "comments", "nextCursor", "error"]

    @field_validator('scope')
    def scope_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['destination', 'external']):
            raise ValueError("must be one of enum values ('destination', 'external')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListComments200ResponseCommentsSubjectsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in comments (list)
        _items = []
        if self.comments:
            for _item_comments in self.comments:
                _items.append(_item_comments.to_dict() if _item_comments is not None else None)
            _dict['comments'] = _items
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        # set to None if external_post_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_post_id is None and "external_post_id" in self.model_fields_set:
            _dict['externalPostId'] = None

        # set to None if next_cursor (nullable) is None
        # and model_fields_set contains the field
        if self.next_cursor is None and "next_cursor" in self.model_fields_set:
            _dict['nextCursor'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListComments200ResponseCommentsSubjectsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "scope": obj.get("scope"),
            "subjectId": obj.get("subjectId"),
            "accountId": obj.get("accountId"),
            "platform": obj.get("platform"),
            "externalPostId": obj.get("externalPostId"),
            "status": obj.get("status"),
            "comments": [Comment.from_dict(_item) for _item in obj["comments"]] if obj.get("comments") is not None else None,
            "nextCursor": obj.get("nextCursor"),
            "error": GetAnalytics200ResponseAnalyticsSubjectsInnerError.from_dict(obj["error"]) if obj.get("error") is not None else None
        })
        return _obj


