# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from onepostly.models.list_inbox_conversations200_response_convos_inner import ListInboxConversations200ResponseConvosInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListInboxConversations200Response(BaseModel):
    """
    ListInboxConversations200Response
    """ # noqa: E501
    account_id: StrictStr = Field(alias="accountId")
    convos: List[ListInboxConversations200ResponseConvosInner]
    cursor: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["accountId", "convos", "cursor"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListInboxConversations200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in convos (list)
        _items = []
        if self.convos:
            for _item_convos in self.convos:
                _items.append(_item_convos.to_dict() if _item_convos is not None else None)
            _dict['convos'] = _items
        # set to None if cursor (nullable) is None
        # and model_fields_set contains the field
        if self.cursor is None and "cursor" in self.model_fields_set:
            _dict['cursor'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListInboxConversations200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accountId": obj.get("accountId"),
            "convos": [ListInboxConversations200ResponseConvosInner.from_dict(_item) for _item in obj["convos"]] if obj.get("convos") is not None else None,
            "cursor": obj.get("cursor")
        })
        return _obj


