# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from onepostly.models.list_inbox_conversations200_response_convos_inner_last_message import ListInboxConversations200ResponseConvosInnerLastMessage
from onepostly.models.list_inbox_conversations200_response_convos_inner_members_inner import ListInboxConversations200ResponseConvosInnerMembersInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListInboxConversations200ResponseConvosInner(BaseModel):
    """
    ListInboxConversations200ResponseConvosInner
    """ # noqa: E501
    id: StrictStr
    members: List[ListInboxConversations200ResponseConvosInnerMembersInner]
    muted: StrictBool
    unread_count: Union[StrictFloat, StrictInt] = Field(alias="unreadCount")
    last_message: Optional[ListInboxConversations200ResponseConvosInnerLastMessage] = Field(alias="lastMessage")
    __properties: ClassVar[List[str]] = ["id", "members", "muted", "unreadCount", "lastMessage"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListInboxConversations200ResponseConvosInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in members (list)
        _items = []
        if self.members:
            for _item_members in self.members:
                _items.append(_item_members.to_dict() if _item_members is not None else None)
            _dict['members'] = _items
        # override the default output from pydantic by calling `to_dict()` of last_message
        if self.last_message:
            _dict['lastMessage'] = self.last_message.to_dict()
        # set to None if last_message (nullable) is None
        # and model_fields_set contains the field
        if self.last_message is None and "last_message" in self.model_fields_set:
            _dict['lastMessage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListInboxConversations200ResponseConvosInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "members": [ListInboxConversations200ResponseConvosInnerMembersInner.from_dict(_item) for _item in obj["members"]] if obj.get("members") is not None else None,
            "muted": obj.get("muted"),
            "unreadCount": obj.get("unreadCount"),
            "lastMessage": ListInboxConversations200ResponseConvosInnerLastMessage.from_dict(obj["lastMessage"]) if obj.get("lastMessage") is not None else None
        })
        return _obj


