# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListWebhookDeliveries200ResponseDeliveriesInner(BaseModel):
    """
    ListWebhookDeliveries200ResponseDeliveriesInner
    """ # noqa: E501
    id: StrictStr
    endpoint_id: StrictStr = Field(alias="endpointId")
    event_id: StrictStr = Field(alias="eventId")
    event_type: StrictStr = Field(alias="eventType")
    status: StrictStr
    attempt_count: Union[StrictFloat, StrictInt] = Field(alias="attemptCount")
    response_status: Optional[Union[StrictFloat, StrictInt]] = Field(alias="responseStatus")
    last_error: Optional[StrictStr] = Field(alias="lastError")
    created_at: StrictStr = Field(alias="createdAt")
    delivered_at: Optional[StrictStr] = Field(alias="deliveredAt")
    __properties: ClassVar[List[str]] = ["id", "endpointId", "eventId", "eventType", "status", "attemptCount", "responseStatus", "lastError", "createdAt", "deliveredAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListWebhookDeliveries200ResponseDeliveriesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if response_status (nullable) is None
        # and model_fields_set contains the field
        if self.response_status is None and "response_status" in self.model_fields_set:
            _dict['responseStatus'] = None

        # set to None if last_error (nullable) is None
        # and model_fields_set contains the field
        if self.last_error is None and "last_error" in self.model_fields_set:
            _dict['lastError'] = None

        # set to None if delivered_at (nullable) is None
        # and model_fields_set contains the field
        if self.delivered_at is None and "delivered_at" in self.model_fields_set:
            _dict['deliveredAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListWebhookDeliveries200ResponseDeliveriesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "endpointId": obj.get("endpointId"),
            "eventId": obj.get("eventId"),
            "eventType": obj.get("eventType"),
            "status": obj.get("status"),
            "attemptCount": obj.get("attemptCount"),
            "responseStatus": obj.get("responseStatus"),
            "lastError": obj.get("lastError"),
            "createdAt": obj.get("createdAt"),
            "deliveredAt": obj.get("deliveredAt")
        })
        return _obj


