# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from onepostly.models.list_inbox_messages200_response_messages_inner_attachments_inner import ListInboxMessages200ResponseMessagesInnerAttachmentsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListInboxMessages200ResponseMessagesInner(BaseModel):
    """
    ListInboxMessages200ResponseMessagesInner
    """ # noqa: E501
    id: StrictStr
    text: Optional[StrictStr]
    sender_id: StrictStr = Field(alias="senderId")
    sent_at: StrictStr = Field(alias="sentAt")
    attachments: List[ListInboxMessages200ResponseMessagesInnerAttachmentsInner] = Field(description="Media attachments (Instagram and Facebook). Empty for text-only messages.")
    __properties: ClassVar[List[str]] = ["id", "text", "senderId", "sentAt", "attachments"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListInboxMessages200ResponseMessagesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                _items.append(_item_attachments.to_dict() if _item_attachments is not None else None)
            _dict['attachments'] = _items
        # set to None if text (nullable) is None
        # and model_fields_set contains the field
        if self.text is None and "text" in self.model_fields_set:
            _dict['text'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListInboxMessages200ResponseMessagesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "text": obj.get("text"),
            "senderId": obj.get("senderId"),
            "sentAt": obj.get("sentAt"),
            "attachments": [ListInboxMessages200ResponseMessagesInnerAttachmentsInner.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None
        })
        return _obj


