# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NormalizedMetrics(BaseModel):
    """
    NormalizedMetrics
    """ # noqa: E501
    impressions: Optional[Union[StrictFloat, StrictInt]] = None
    reach: Optional[Union[StrictFloat, StrictInt]] = None
    likes: Optional[Union[StrictFloat, StrictInt]] = None
    comments: Optional[Union[StrictFloat, StrictInt]] = None
    shares: Optional[Union[StrictFloat, StrictInt]] = None
    saves: Optional[Union[StrictFloat, StrictInt]] = None
    plays: Optional[Union[StrictFloat, StrictInt]] = None
    engagement: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["impressions", "reach", "likes", "comments", "shares", "saves", "plays", "engagement"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NormalizedMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if impressions (nullable) is None
        # and model_fields_set contains the field
        if self.impressions is None and "impressions" in self.model_fields_set:
            _dict['impressions'] = None

        # set to None if reach (nullable) is None
        # and model_fields_set contains the field
        if self.reach is None and "reach" in self.model_fields_set:
            _dict['reach'] = None

        # set to None if likes (nullable) is None
        # and model_fields_set contains the field
        if self.likes is None and "likes" in self.model_fields_set:
            _dict['likes'] = None

        # set to None if comments (nullable) is None
        # and model_fields_set contains the field
        if self.comments is None and "comments" in self.model_fields_set:
            _dict['comments'] = None

        # set to None if shares (nullable) is None
        # and model_fields_set contains the field
        if self.shares is None and "shares" in self.model_fields_set:
            _dict['shares'] = None

        # set to None if saves (nullable) is None
        # and model_fields_set contains the field
        if self.saves is None and "saves" in self.model_fields_set:
            _dict['saves'] = None

        # set to None if plays (nullable) is None
        # and model_fields_set contains the field
        if self.plays is None and "plays" in self.model_fields_set:
            _dict['plays'] = None

        # set to None if engagement (nullable) is None
        # and model_fields_set contains the field
        if self.engagement is None and "engagement" in self.model_fields_set:
            _dict['engagement'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NormalizedMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "impressions": obj.get("impressions"),
            "reach": obj.get("reach"),
            "likes": obj.get("likes"),
            "comments": obj.get("comments"),
            "shares": obj.get("shares"),
            "saves": obj.get("saves"),
            "plays": obj.get("plays"),
            "engagement": obj.get("engagement")
        })
        return _obj


