# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from onepostly.models.destination_status import DestinationStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PostDestination(BaseModel):
    """
    PostDestination
    """ # noqa: E501
    id: UUID
    connection_id: UUID = Field(alias="connectionId")
    platform: StrictStr
    status: DestinationStatus
    external_post_id: Optional[StrictStr] = Field(alias="externalPostId")
    external_url: Optional[StrictStr] = Field(alias="externalUrl")
    error_code: Optional[StrictStr] = Field(alias="errorCode")
    error_message: Optional[StrictStr] = Field(alias="errorMessage")
    published_at: Optional[datetime] = Field(alias="publishedAt")
    __properties: ClassVar[List[str]] = ["id", "connectionId", "platform", "status", "externalPostId", "externalUrl", "errorCode", "errorMessage", "publishedAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostDestination from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if external_post_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_post_id is None and "external_post_id" in self.model_fields_set:
            _dict['externalPostId'] = None

        # set to None if external_url (nullable) is None
        # and model_fields_set contains the field
        if self.external_url is None and "external_url" in self.model_fields_set:
            _dict['externalUrl'] = None

        # set to None if error_code (nullable) is None
        # and model_fields_set contains the field
        if self.error_code is None and "error_code" in self.model_fields_set:
            _dict['errorCode'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['errorMessage'] = None

        # set to None if published_at (nullable) is None
        # and model_fields_set contains the field
        if self.published_at is None and "published_at" in self.model_fields_set:
            _dict['publishedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostDestination from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "connectionId": obj.get("connectionId"),
            "platform": obj.get("platform"),
            "status": obj.get("status"),
            "externalPostId": obj.get("externalPostId"),
            "externalUrl": obj.get("externalUrl"),
            "errorCode": obj.get("errorCode"),
            "errorMessage": obj.get("errorMessage"),
            "publishedAt": obj.get("publishedAt")
        })
        return _obj


