# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from onepostly.models.set_connection_messenger_profile200_response_profile_ice_breakers_inner import SetConnectionMessengerProfile200ResponseProfileIceBreakersInner
from onepostly.models.set_connection_messenger_profile200_response_profile_persistent_menu_inner import SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SetConnectionMessengerProfile200ResponseProfile(BaseModel):
    """
    SetConnectionMessengerProfile200ResponseProfile
    """ # noqa: E501
    ice_breakers: List[SetConnectionMessengerProfile200ResponseProfileIceBreakersInner] = Field(alias="iceBreakers")
    persistent_menu: List[SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner] = Field(alias="persistentMenu")
    __properties: ClassVar[List[str]] = ["iceBreakers", "persistentMenu"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SetConnectionMessengerProfile200ResponseProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ice_breakers (list)
        _items = []
        if self.ice_breakers:
            for _item_ice_breakers in self.ice_breakers:
                _items.append(_item_ice_breakers.to_dict() if _item_ice_breakers is not None else None)
            _dict['iceBreakers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in persistent_menu (list)
        _items = []
        if self.persistent_menu:
            for _item_persistent_menu in self.persistent_menu:
                _items.append(_item_persistent_menu.to_dict() if _item_persistent_menu is not None else None)
            _dict['persistentMenu'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SetConnectionMessengerProfile200ResponseProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "iceBreakers": [SetConnectionMessengerProfile200ResponseProfileIceBreakersInner.from_dict(_item) for _item in obj["iceBreakers"]] if obj.get("iceBreakers") is not None else None,
            "persistentMenu": [SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner.from_dict(_item) for _item in obj["persistentMenu"]] if obj.get("persistentMenu") is not None else None
        })
        return _obj


