# coding: utf-8

"""
    Onepostly API

    One API for all social media. Authenticate with a workspace API key (`op_…`).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from onepostly.models.external_post import ExternalPost
from onepostly.models.sync_external200_response_synced import SyncExternal200ResponseSynced
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SyncExternal200Response(BaseModel):
    """
    SyncExternal200Response
    """ # noqa: E501
    synced: SyncExternal200ResponseSynced
    found: Optional[StrictBool] = None
    post: Optional[ExternalPost] = None
    posts: Optional[List[Optional[ExternalPost]]] = None
    __properties: ClassVar[List[str]] = ["synced", "found", "post", "posts"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SyncExternal200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of synced
        if self.synced:
            _dict['synced'] = self.synced.to_dict()
        # override the default output from pydantic by calling `to_dict()` of post
        if self.post:
            _dict['post'] = self.post.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in posts (list)
        _items = []
        if self.posts:
            for _item_posts in self.posts:
                _items.append(_item_posts.to_dict() if _item_posts is not None else None)
            _dict['posts'] = _items
        # set to None if post (nullable) is None
        # and model_fields_set contains the field
        if self.post is None and "post" in self.model_fields_set:
            _dict['post'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SyncExternal200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "synced": SyncExternal200ResponseSynced.from_dict(obj["synced"]) if obj.get("synced") is not None else None,
            "found": obj.get("found"),
            "post": ExternalPost.from_dict(obj["post"]) if obj.get("post") is not None else None,
            "posts": [ExternalPost.from_dict(_item) for _item in obj["posts"]] if obj.get("posts") is not None else None
        })
        return _obj


